services:
  mysql:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testing
    networks:
      - net
    ports:
      - "3306:3306"

  java-app:
    image: project
    container_name: app
    depends_on:
      - mysql
    networks:
      - net
    ports:
      - "8080:8080"

networks:
  net:
    driver: bridge
